// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMCLiYsujkDX-UWeFhwg0iH3t6xiuvtA',
    appId: '1:750802718505:android:38be20c4abe124e5e77138',
    messagingSenderId: '750802718505',
    projectId: 'passwordmanager-a461f',
    storageBucket: 'passwordmanager-a461f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUIOKm3qXTZYZTF6O--_YsI4vW60QwN6Y',
    appId: '1:750802718505:ios:eb7df154601e6ed2e77138',
    messagingSenderId: '750802718505',
    projectId: 'passwordmanager-a461f',
    storageBucket: 'passwordmanager-a461f.appspot.com',
    iosClientId:
        '750802718505-ssdumdsc6lc9oc7207dvf96b2nk7dkjc.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );
}
